//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WomenCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WomenCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alarm {
            get {
                object obj = ResourceManager.GetObject("alarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baby_Image {
            get {
                object obj = ResourceManager.GetObject("baby_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap babyFace_Image {
            get {
                object obj = ResourceManager.GetObject("babyFace_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap babyNot_Image {
            get {
                object obj = ResourceManager.GetObject("babyNot_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap babyQuestion_Image {
            get {
                object obj = ResourceManager.GetObject("babyQuestion_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap boy_Image {
            get {
                object obj = ResourceManager.GetObject("boy_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;calendars xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&gt;
        ///	&lt;calendar Name=&quot;mama.ru&quot; Site=&quot;http://www.mama.ru/&quot;&gt;
        ///		&lt;week Number=&quot;1&quot;&gt;http://www.mama.ru/pregn/1/&lt;/week&gt;
        ///		&lt;week Number=&quot;2&quot;&gt;http://www.mama.ru/pregn/2/&lt;/week&gt;
        ///		&lt;week Number=&quot;3&quot;&gt;http://www.mama.ru/pregn/3/&lt;/week&gt;
        ///		&lt;week Number=&quot;4&quot;&gt;http://www.mama.ru/pregn/4/&lt;/week&gt;
        ///		&lt;week Number=&quot;5&quot;&gt;http://www.mama.ru/pregn/5/&lt;/week&gt;
        ///		&lt;week Number=&quot;6&quot;&gt;htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap calendarEdit_Image {
            get {
                object obj = ResourceManager.GetObject("calendarEdit_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Checkmark_32 {
            get {
                object obj = ResourceManager.GetObject("Checkmark_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drop_Image {
            get {
                object obj = ResourceManager.GetObject("drop_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dropNot_Image {
            get {
                object obj = ResourceManager.GetObject("dropNot_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editGreen16x16 {
            get {
                object obj = ResourceManager.GetObject("editGreen16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap egestaDrop0 {
            get {
                object obj = ResourceManager.GetObject("egestaDrop0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap egestaDrop1 {
            get {
                object obj = ResourceManager.GetObject("egestaDrop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap egestaDrop2 {
            get {
                object obj = ResourceManager.GetObject("egestaDrop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap egestaDrop3 {
            get {
                object obj = ResourceManager.GetObject("egestaDrop3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap egestaDrop4 {
            get {
                object obj = ResourceManager.GetObject("egestaDrop4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exportGreen {
            get {
                object obj = ResourceManager.GetObject("exportGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap girl_Image {
            get {
                object obj = ResourceManager.GetObject("girl_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_01 {
            get {
                object obj = ResourceManager.GetObject("Green_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_04 {
            get {
                object obj = ResourceManager.GetObject("Green_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap month_dropdown {
            get {
                object obj = ResourceManager.GetObject("month_dropdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newGreen {
            get {
                object obj = ResourceManager.GetObject("newGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_Image {
            get {
                object obj = ResourceManager.GetObject("note_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noteNot_Image {
            get {
                object obj = ResourceManager.GetObject("noteNot_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openGreen {
            get {
                object obj = ResourceManager.GetObject("openGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OvlArrowDown {
            get {
                object obj = ResourceManager.GetObject("OvlArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OvlArrowDownOver {
            get {
                object obj = ResourceManager.GetObject("OvlArrowDownOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OvlArrowUp {
            get {
                object obj = ResourceManager.GetObject("OvlArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OvlArrowUpOver {
            get {
                object obj = ResourceManager.GetObject("OvlArrowUpOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ovulashki_logo {
            get {
                object obj = ResourceManager.GetObject("ovulashki_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ovulashki_logo2 {
            get {
                object obj = ResourceManager.GetObject("ovulashki_logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printGreen {
            get {
                object obj = ResourceManager.GetObject("printGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printPreviewGreen {
            get {
                object obj = ResourceManager.GetObject("printPreviewGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveGreen {
            get {
                object obj = ResourceManager.GetObject("saveGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updateGreen {
            get {
                object obj = ResourceManager.GetObject("updateGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
